### ISSUE TITLE
flatMap

### ISSUE THREAD

**Issue by JaapWijnen** [pointfreeco/swift-validated#14]
Any specific reason methods like flatMap and sequence (from the pointfree.co episodes)aren't included in the package?

**Comment by stephencelis** [comment]
Hi @JaapWijnen! We have a discussion about this in our episodes on `flatMap`, particularly part 5: https://www.pointfree.co/episodes/ep46-the-many-faces-of-flat-map-part-5

In short, types with `flatMap` can automatically derive `map` and `zip`:

```swift
func map<NewValue>(_ transform: (Value) -> NewValue) -> MyType<NewValue> {
  self.flatMap { /* return new MyType by transforming self.value and bundling it up */ }
}

func zip<A, B>(_ a: MyType<A>, _ b: MyType<B>) -> MyType<(A, B)> {
  a.flatMap { a in b.flatMap { b in /* return new MyType by bundling up 'a' and 'b' */ } }
}
```

However, this `zip` derived for `Validated` is _not_ the same as the `zip` we have defined:

- Zip as we've defined accumulates errors
- Zip derived from `flatMap` will bail out on the first error

Because of this `flatMap` can lead to missing out on the very validation information the type is designed for 😅 Luckily, we have the `Result` type for this kind of thing.

I'm going to convert this to a discussion, but maybe we should mention the absence of `flatMap` in the README. Thanks for the discussion!
